services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest # Or specify a different version
    container_name: mssql-server
    command: /bin/bash ./entrypoint.sh
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
      - MSSQL_PID=Developer # Or specify another edition like Express, Standard, Enterprise
      - TZ=America/Mexico_City
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql # Persist data outside the container
      - ./src/db/entrypoint.sh:/entrypoint.sh
      - ./src/db/db-init.sh:/db-init.sh
      - ./src/db/db_init.sql:/db_init.sql

    networks:
      - redarbor-network
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "30"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Passw0rd", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redarbor-webapi:
    build:
      context: ./src/
      dockerfile: Dockerfile
    container_name: redarbor-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Products=Server=db;Initial Catalog=products_db;User Id=sa;Password=Passw0rd;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    # depends_on:
    #   db:
    networks:
      - redarbor-network
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "30"


volumes:
  mssql-data:

networks:
  redarbor-network:
    driver: bridge